name: CI

on:
  push:
    paths:
      - ".github/**"
      - "blackcraft_exporter/**"
      - poetry.lock
      - pyproject.toml
      - Dockerfile
      - .dockerignore
  pull_request:

jobs:
  image:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fallenbreath
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            fallenbreath/blackcraft_exporter
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/JRubics/poetry-publish
      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v2.1
        with:
          python_version: '3.11'
          poetry_version: '==2.1.1'
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
